# Generated by Django 3.2 on 2021-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20210903_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
